### ISSUE TITLE
Equalizer Example Autosave Creating Multiple magic.sav.xml Files

### ISSUE THREAD

**Issue by r00tk1ll** [ffAudio/foleys_gui_magic#68]
When compiling and testing with the Equalizer Example project, the auto save function is continuously creating magic.sav.xml files. 

I.E.
![image](https://user-images.githubusercontent.com/12835789/140699577-1c79ea66-5fb7-467c-b64b-b846d929e3eb.png)
  
Is it possible to only use the magic.xml that is added as a resource though the Projucer Interface?

As you can see in the screenshot, I have 17+ magic.sav.xml files

**Comment by ffAudio** [comment]
Thanks for the report. 
When you end the PGM the editor will check if the auto save file is identical with the magic.xml that was loaded initially. If they are identical the auto save file will be removed.
When you edit the contents of PGM but don't save it, the modifications will stay in the folder. Otherwise the feature would be pretty useless.
To continue with the state of an autosave file, just load it using the File -> Load menu.

Since when the plugin is closed, PGM has no chance to intercept and ask if you want to save or discard, so I see no way of automating that step. If you have an idea I am all ears.

**Comment by r00tk1ll** [comment]
That's actually fine for me as I'm in a development environment anyways, I can just delete the extra files.

The only question I have is when deploying the finished application to end users, there is some way to keep the auto save feature from adding an indefinite amount of magic.sav(x).xml to the installation directory of the users local machine.

As a side note, I am a week into utilizing PGM in my project and really enjoying it. Looking forward to purchasing a license and adopting it for all of my audio projects.

**Comment by ffAudio** [comment]
> The only question I have is when deploying the finished application to end users, there is some way to keep the auto save feature from adding an indefinite amount of magic.sav(x).xml to the installation directory of the users local machine.

That shouldn't be a problem. First the auto save files are not listed in the BinaryResources (unless you glob them into cmake, better don't do that). And they are created by the editor that is floating next to the plugin editor.
When you are done developing you switch the `FOLEYS_SHOW_GUI_EDITOR_PALLETTE=0`. I usually add that to the release build so I cannot forget it. That way on a clients machine there will never be an auto save file created.

> As a side note, I am a week into utilizing PGM in my project and really enjoying it. Looking forward to purchasing a license and adopting it for all of my audio projects.

That's awesome, glad you like it!
